# Generated by Django 5.1.2 on 2024-10-31 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IndustrySolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceExtensionFor1C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='1С:Предприятие', max_length=20)),
                ('delivery_method', models.CharField(default='Электронная поставка', max_length=50)),
                ('company_type', models.ManyToManyField(blank=True, related_name='service_1C', to='App1C.companytype')),
                ('industry_solutions', models.ManyToManyField(blank=True, related_name='service_1C', to='App1C.industrysolution')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='Services.service')),
                ('task_solutions', models.ManyToManyField(blank=True, related_name='service_1C', to='App1C.tasksolution')),
            ],
        ),
    ]
