# Generated by Django 5.1.2 on 2024-10-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_companytype_industrysolution_tasksolution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainservice',
            name='slug',
            field=models.SlugField(default='q'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ServiceExtensionFor1C',
        ),
        migrations.DeleteModel(
            name='TaskSolution',
        ),
    ]
