# Generated by Django 5.1.2 on 2024-11-18 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_remove_serviceextensionfor1c_company_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='main_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Services.mainservice'),
            preserve_default=False,
        ),
    ]
