# Generated by Django 5.1.2 on 2024-11-22 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_service_main_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('canceled', 'Отменено')], default='pending', max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('main_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='Services.mainservice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='Services.service')),
            ],
        ),
    ]
