# Generated by Django 5.1.2 on 2024-11-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0007_alter_mainservice_slug_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainservice',
            name='status',
            field=models.BooleanField(default='True'),
        ),
    ]
