# Generated by Django 5.1.2 on 2024-11-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='Часы работы')),
                ('telegram', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
